### ISSUE TITLE
How to plot Spectrogram ? No plotting code is given in notebook

### ISSUE THREAD

**Issue by harshal5789** [biosignalsplux/biosignalsnotebooks#2]
I want to know how to plot spectrogram with power bar (image-1) & power spectral density plot (image-2) given in notebook . there is no code available in notebook for plotting certain graphs in notebooks..
find attachments for reference.

![image](https://user-images.githubusercontent.com/62555471/78631104-036d5080-78b9-11ea-8518-89b71bff54bc.png)

![image](https://user-images.githubusercontent.com/62555471/78632168-eede8780-78bb-11ea-9710-ff03f0fdb0ad.png)

**Comment by GRamosPlux** [comment]
Dear **@harshal5789**,

I am sorry for the undesirable delay of this answer, we hope that it still could be helpful!

Graphical representation functionalities are extremely useful for a quick and intuitive analysis of data.
This question is very appropriate, it will be a pleasure to help you.

In the **HTML/Web** version of the **Notebooks**, some code cells are hidden to decrease the volume of code not directly related with the topic under analysis.
Due to this "hide" feature, many graphical functions are not immediately visible in the website, but, fortunately you can access them through the **"Program"** button located in the top-left corner of each Notebook header:
![Program functionality](https://i.ibb.co/rfcSyb8/program-functionality.gif)

A remote server will be launched, containing the Notebook with all cells visible.
In this environment you had the opportunity to edit the code and make your own experiences!

I truly hope that you considered these information's helpful, however, if you don't consider them appropriate or if further questions arise, please, do not hesitate to alert us.

                        My best and sincere regards,
                        **GRamosPlux**

**Comment by GRamosPlux** [comment]
Dear **@harshal5789**,

Hoping that the previous information was helpful, for now I will close this issue.
However, if the issue persists, I will reopen it immediately.

Thank you very much for your positive intervention!

My best and sincere regards,
**GRamosPlux**
