### ISSUE TITLE
Figures do not show.

### ISSUE THREAD

**Issue by Achilleswcyy** [biosignalsplux/biosignalsnotebooks#6]
I test "Fatigue Evaluation - Evolution of Median Power Frequency" in python 3.8, and no errors occur,but there are no figures show.

**Comment by GRamosPlux** [comment]
Dear @Achilleswcyy,

Thank you very much for being an important part of our esteemed community of users and for opening this important discussion!

The information provided was really helpful.
Unfortunately, the **biosignalsnotebooks** package uses the **Bokeh** [(auxiliary link)](https://docs.bokeh.org/en/latest/) library for all features linked with the plot/chart generation, which is not fully compatible with **Spyder IDE**.
Our sincere apologies for this setback.

In order to ensure the visualization of the charts, hoping that you don't consider the following suggestion inappropriate, we recommend the usage of the **biosignalsnotebooks** package in the **Jupyter Notebook** environment.
The following link shows how-to install and launch it through **pip**:

- [Jupyter Notebook | Install and Launch](https://jupyter.org/install#jupyter-notebook)

I will carefully wait for your extremely valuable feedback about the viability of the previous path!

**My best and sincere regards,**
@GRamosPlux
